word_list = [
"10 Things I Hate About You",
"10th Kingdom, The",
"127 Hours",
"13 Going on 30",
"13th Warrior, The",
"1408 (film)",
"17 Again",
"1941 (film)",
"20,000 Leagues Under the Sea (film)",
"2001: A Space Odyssey",
"2012 (film)",
"21 Grams",
"25th Hour",
"27 Dresses",
"28 Days Later",
"300",
"3000 Miles to Graceland",
"3:10 to Yuma",
"40 Year-Old Virgin, The",
"400 Blows, The",
"50 First Dates",
"(500) Days of Summer",
"7 Pounds",
"8 Mile",
"A Nightmare on Elm Street",
"A Nightmare on Elm Street (2010 film)",
"About Schmidt",
"Absence of Malice",
"Accidental Tourist, The",
"Ace Ventura: Pet Detective",
"Ace Ventura: When Nature Calls",
"Across the Universe",
"Adam's Rib",
"Addams Family, The",
"Adventures of Robin Hood, The",
"The Affair of the Necklace",
"After Hours",
"Aguirre, the Wrath of God",
"A.I. Artificial Intelligence",
"Air Force One",
"Airplane!",
"Airplane II: The Sequel",
"Airport",
"Airport 1975",
"Airport '77",
"Akeelah and the Bee",
"Aladdin (film)",
"Aladdin and the King of Thieves",
"Alexander",
"Alice in Wonderland (1951 film)",
"Alice in Wonderland (1976 film)",
"Alice in Wonderland (2010 film)",
"Alien",
"Aliens",
"Alien 3",
"Alive (1993 film)",
"Almost Heroes",
"Alvin and the Chipmunks (film)",
"Alvin and the Chipmunks: The Squeakquel",
"All About Steve",
"All the President's Men",
"All the Right Moves",
"Almost Famous",
"Along Came a Spider",
"Alpha Dog",
"Alpha and Omega",
"The Amityville Horror (2005 film)",
"American Beauty",
"American Gangster",
"American Graffiti",
"American History X",
"American in Paris, An",
"American Me",
"American Pie",
"American Pie 2",
"American Psycho",
"American Tail, An",
"American Tail: Fievel Goes West, An",
"American Wedding",
"Analyze This",
"Anastasia",
"Anchorman: The Legend of Ron Burgundy",
"...And Justice For All",
"And the Band Played On",
"Angel Heart",
"Angels & Demons",
"Angels in the Outfield (1994 film)",
"Angels with Dirty Faces",
"Angus, Thongs and Perfect Snogging",
"Animal House",
"Anna and the King",
"Annie",
"Annie Hall",
"Another Cinderella Story",
"Antitrust",
"Antz",
"Apocalypse Now",
"Apocalypto",
"Apollo 13",
"Are We Done Yet?",
"Are We There Yet?",
"Aristocats, The",
"Armageddon",
"Around the World in 80 Days (2004 film)",
"Arthur",
"As Good As It Gets",
"At First Sight",
"Atlantic City",
"Atlantis: The Lost Empire",
"Atonement",
"Attack of the 50 Foot Woman",
"Austin Powers: International Man of Mystery",
"Austin Powers: The Spy Who Shagged Me",
"Austin Powers in Goldmember",
"Avatar",
"Aviator, The",
"Away from Her",
"Babe",
"Babylon A.D",
"Bachelor Mother",
"Backdraft",
"Back to the Future",
"Back to the Future Part II",
"Back to the Future Part III",
"Back to School",
"Bad Boys",
"Bad Boys II",
"Bad Day at Black Rock",
"Bad Santa",
"Bad Taste",
"Badlands",
"Balto",
"Bambi",
"Bambi II",
"Barbarella",
"Barcelona",
"Barton Fink",
"Barry Lyndon",
"BASEketball",
"Basic Instinct",
"Basic Instinct 2",
"Batman (1989)",
"Batman Begins",
"Batman Forever",
"Batman Returns",
"Battle of San Pietro, The",
"Battle Royale",
"Beach, The",
"Beaches",
"Beast of Yucca Flats, The",
"Beautiful Girls",
"Beautiful Mind, A",
"Beauty and the Beast",
"Beavis and Butthead Do America",
"Becoming Jane",
"Bedazzled (1967 film)",
"Bedazzled (2000 film)",
"Bedknobs and Broomsticks",
"Bedtime Stories (film)",
"Bee Movie",
"Bee Season",
"Beerfest",
"Beetlejuice",
"Before Sunrise",
"Before Sunset",
"Behind Enemy Lines",
"Being John Malkovich",
"Being There",
"Be Kind Rewind",
"Ben-Hur",
"Bend It Like Beckham",
"Benny & Joon",
"Beowulf",
"Best in Show",
"Best Years of Our Lives, The",
"Better Off Dead",
"Better Than Chocolate",
"Better Tomorrow, A",
"Beverly Hills Chihuahua",
"Beverly Hills Cop II",
"Beverly Hills Cop III",
"Beyond the Valley of the Dolls",
"Bicentennial Man",
"Big",
"Big Daddy",
"Big Fish",
"Big Lebowski, The",
"Big Night",
"Big Sleep, The",
"Big Top Pee-wee",
"Big Trouble",
"Big Trouble in Little China",
"Bill and Ted's Excellent Adventure",
"Billy Madison",
"Birds, The",
"Black Book",
"Black Cat, The",
"Black Christmas",
"Black Christmas (2006 film)",
"Black Hawk Down",
"Black Rain",
"Black Sheep",
"Black Swan",
"Blade",
"Blade II",
"Blade: Trinity",
"Blade Runner",
"Blades of Glory",
"Blair Witch Project, The",
"Blind Date (1987 film)",
"Blazing Saddles",
"Blood Diamond",
"Blood Feast",
"Blood Simple",
"Blow",
"Blown Away",
"Blue Collar",
"Blue Velvet",
"Blue Lagoon, The",
"Blues Brothers, The",
"Blues Brothers 2000",
"Body Heat",
"Body of Lies",
"Boiler Room",
"Bolt (2008 film)",
"Boogeyman",
"The Book of Pooh: Stories from the Heart",
"Book of Shadows: Blair Witch 2",
"Boondock Saints, The",
"Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
"Born on the Fourth of July",
"Bottle Rocket",
"Bound",
"Bourne Identity, The",
"Bourne Supremacy, The",
"Bourne Ultimatum, The",
"Bowling for Columbine",
"Boy Named Charlie Brown, A",
"Boys Town",
"Boyz n the Hood",
"Braindead",
"Brassed Off",
"Braveheart",
"Brazil",
"Breakfast at Tiffany's",
"Breakfast Club, The",
"Breaking Away",
"Breaking Up",
"Bride Wars",
"Bridge on the River Kwai, The",
"Bridge to Terabithia (2007 film)",
"Bridget Jones's Diary",
"Bring It On",
"Bringing Up Baby",
"Brokeback Mountain",
"Broken Arrow",
"Bronx Tale, A",
"Brother Bear",
"Brother Bear 2",
"Brothers McMullen, The",
"Brubaker",
"Bruce Almighty",
"Buckaroo Banzai",
"Bucket List, The",
"Buffalo 66",
"Buffy the Vampire Slayer (film)",
"Bug",
"Bug's Life, A",
"Bull Durham",
"Bullitt",
"Burn After Reading",
"But I'm a Cheerleader",
"Butch Cassidy and the Sundance Kid",
"Butterfly Effect, The",
"By Dawn's Early Light",
"Cabinet of Dr. Caligari, The",
"Cable Guy, The",
"Caddyshack",
"Camelot",
"Camp Rock",
"Can't Buy Me Love",
"Candy",
"Capricorn One",
"Care Bears Movie, The",
"Care Bears Movie II: A New Generation",
"Carlito's Way",
"Carrie",
"Cars",
"Cars 2",
"Casablanca",
"Casanova",
"Casino",
"Casino Royale",
"Cast Away",
"Casualties of War",
"Catch-22",
"Catch Me If You Can",
"Cat on a Hot Tin Roof",
"Cat People",
"Cat Returns, The",
"Cats & Dogs",
"Catwoman",
"Cecil B. Demented",
"Changing Lanes",
"Charlie and the Chocolate Factory",
"Charlie's Angels",
"Charlie's Angels: Full Throttle",
"Charlie Wilson's War",
"Chariots of Fire",
"Charlotte's Web (1973 film)",
"Chasing Amy",
"Chasing Liberty",
"Cheaper By The Dozen",
"Chicago",
"Chicken Run",
"Children of Dune",
"Children of Men",
"Children's Hour, The",
"Child's Play",
"Chinatown",
"Chitty Chitty Bang Bang",
"Chocolat",
"Choke",
"Christmas Story, A",
"Christmas with the Kranks",
"The Chronicles of Narnia: Prince Caspian",
"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
"Chronicles of Riddick, The",
"Chumscrubber, The",
"Cider House Rules, The",
"Cinderella (1950 film)",
"A Cinderella Story",
"Citizen Kane",
"City of Angels",
"City of Ember",
"City on Fire",
"City of God",
"City Slickers",
"Clash of the Titans (2010 film)",
"Clear and Present Danger",
"Cleopatra (1963 film)",
"Click",
"Client, The",
"Clerks",
"Clerks II",
"Clockwise",
"Clockwork Orange, A",
"Close Encounters Of The Third Kind",
"Closer",
"Cloudy with a Chance of Meatballs (film)",
"Cloverfield",
"Clue",
"Clueless",
"Coach Carter",
"Cocktail",
"Color Purple, The",
"Cold Mountain",
"Collateral",
"Coming Home",
"Commando",
"Commitments, The",
"Con Air",
"Conan the Barbarian",
"Conan the Destroyer (1984)",
"Coneheads",
"Confessions of a Dangerous Mind",
"Confetti",
"Conquest of Space",
"Conspiracy Theory",
"Constant Gardener, The",
"Cool and the Crazy‎",
"Cool Hand Luke",
"Cool Runnings",
"Coraline",
"Core, The",
"Corpse Bride",
"Count of Monte Cristo, The",
"Cowboy Bebop: The Movie",
"Coyote Ugly",
"Craft, The",
"Crank",
"Crash (1996 film)",
"Crash (2004 film)",
"Crimes and Misdemeanors",
"Crimewave",
"Crimson Tide",
"Criss Cross",
"Crocodile Dundee",
"Cross of Iron",
"Cry Wolf",
"Crow, The",
"Cruel Intentions",
"Crying Game, The",
"Cube",
"Cube 2: Hypercube",
"Cube Zero",
"Cure, The",
"The Curious Case of Benjamin Button (film)",
"Cursed",
"Cutting Edge, The",
"Da Vinci Code, The",
"Daddy Day Camp",
"Daddy Day Care",
"Dan in Real Life",
"Dance of the Dead",
"Dances with Wolves",
"Dangerous Beauty",
"Daredevil",
"Darjeeling Limited, The",
"Dark City",
"Dark Knight, The",
"Das Boot",
"Das Leben der Anderen",
"Dave",
"Dawn of the Dead (1978 film)",
"Dawn of the Dead (2004 film)",
"Day After Tomorrow, The",
"Day of the Jackal, The",
"Days of Thunder",
"Dazed and Confused",
"Dead Alive",
"Dead Poets Society",
"Deadfall",
"Descent",
"Death Becomes Her",
"Death Rides a Horse",
"Death to Smoochy",
"Death Wish (movie series)",
"D.E.B.S.",
"Dedication",
"Deep Impact",
"Deep Throat",
"Deer Hunter, The",
"Deewar",
"Defending Your Life",
"Defendor",
"Déjà Vu",
"Deliverance",
"Departed, The",
"Der Fuehrer's Face",
"Desperate Living",
"Despicable Me",
"Deuce Bigalow: European Gigolo",
"Deuce Bigalow: Male Gigolo",
"Devil's Advocate, The",
"Devil's Own, The",
"Devil's Rejects, The",
"Devil in a Blue Dress",
"Devil Wears Prada, The",
"Dial M for Murder",
"Diary of a Wimpy Kid",
"Diamonds Are Forever",
"Dick",
"Dick Tracy",
"Die Hard",
"Die Hard 2: Die Harder",
"Die Hard With a Vengeance",
"Live Free or Die Hard",
"Dinosaur",
"Dirty Dancing",
"Dirty Harry",
"Dirty Rotten Scoundrels",
"Dirty Shame, A",
"Disaster Movie",
"Disclosure",
"District 9",
"Disturbia",
"Disturbing Behavior",
"Divine Secrets of the Ya Ya Sisterhood",
"Doctor Dolittle (1967)",
"Doctor Dolittle (1998)",
"Dr. Dolittle 2",
"Doctor Zhivago",
"Dodgeball: A True Underdog Story",
"Dogma",
"Dogville",
"Dog Day Afternoon",
"Don Juan DeMarco (1995 movie)",
"Donald in Mathmagic Land",
"Donnie Brasco",
"Donnie Darko",
"Don't Be A Menace To South Central While Drinking Your Juice In The Hood",
"Don't Say a Word",
"Don't Tell Mom the Babysitter's Dead",
"Doom (film)",
"Doors, The",
"Dorian Gray (2009)",
"Double Indemnity",
"Down Periscope",
"Down to Earth",
"Down With Love",
"Dr. No",
"Dr. Strangelove: Or How I Learned to Stop Worrying and Love the Bomb",
"Dracula (1931)",
"Dracula (1979)",
"Dracula (1992)",
"Dracula AD 1972",
"Dracula: Dead and Loving It",
"Dragnet",
"Dreamers, The",
"Driving Miss Daisy",
"Drop Dead Fred",
"Drop Dead Gorgeous",
"Drowning Mona",
"Duck Soup",
"Dude, Where's My Car?",
"Duel",
"Dukes of Hazzard, The",
"Dumb and Dumber",
"Dumb and Dumberer",
"Dumbo",
"Dummy",
"Dune",
"Duplex",
"Dylan Dog: Dead of Night",
"Earthquake",
"East of Eden",
"Eastern Promises",
"Easy Rider",
"Ed Wood",
"Eddie and the Cruisers",
"Edge, The",
"Education, An",
"Edward Scissorhands",
"Eight Crazy Nights",
"Eight Legged Freaks",
"Elf",
"Elizabeth",
"Elizabethtown",
"Emperor's New Groove, The",
"Empire Records",
"Enchanted",
"End of Days",
"Enemy at the Gates",
"Enemy of the State",
"Englishman Who Went Up a Hill But Came Down a Mountain, The",
"English Patient, The",
"Enter the Dragon",
"Epic Movie",
"Equilibrium",
"Eragon (film)",
"Erin Brockovich",
"Elvis",
"Ernest Goes to Camp",
"Ernest Goes to Jail",
"Ernest Saves Christmas",
"Ernest Scared Stupid",
"E.T. the Extra-Terrestrial",
"Eternal Sunshine of the Spotless Mind",
"Eurotrip",
"Evan Almighty",
"Event Horizon",
"Ever After",
"Everything Is Illuminated",
"Evil Dead, The",
"Evil Dead 2",
"Evolution",
"Exorcist, The",
"Exorcist III, The",
"Expelled: No Intelligence Allowed",
"An Extremely Goofy Movie",
"Eyes Wide Shut",
"Face/Off",
"Factory Girl",
"Fahrenheit 451",
"Fahrenheit 9/11",
"Fail-Safe",
"Failure to Launch",
"Falling Down",
"Fame",
"Family Man, The",
"Fantastic Four",
"Fargo",
"Fast and Furious",
"Fast and the Furious, The",
"Fast and the Furious: Tokyo Drift, The",
"Fast, Cheap and Out of Control",
"Fast Five",
"Fast Times at Ridgemont High",
"Faster, Pussycat! Kill! Kill!",
"Fat Albert",
"Father of the Bride (1991 film)",
"Fear and Loathing in Las Vegas",
"Fearless (2006 film)",
"Femme Fatale",
"FernGully: The Last Rainforest",
"Ferris Bueller's Day Off",
"Few Good Men, A",
"Fiddler on the Roof",
"Field of Dreams",
"Fifth Element, The",
"Fight Club",
"Final Destination",
"Final Destination 2",
"Final Destination 3",
"The Final Destination",
"Final Fantasy: The Spirits Within",
"Final Fantasy VII: Advent Children",
"Finding Forrester",
"Finding Nemo",
"Finding Neverland",
"Fine Mess, A",
"Firm, The",
"First Blood",
"First Knight",
"First Wives Club, The",
"Fish Called Wanda, A",
"Fisher King, The",
"Fistful of Dollars, A",
"Five Easy Pieces",
"Five Minutes of Heaven",
"Flags of Our Fathers",
"Flash Gordon",
"Flatliners",
"Fletch",
"Fletch Lives aka Fletch 2",
"Flicka",
"Flushed Away",
"Flyboys",
"Fog of War, The",
"Football Factory, The",
"Footloose",
"Forbidden Kingdom, The",
"Forgetting Sarah Marshall",
"Forrest Gump",
"Four Brothers",
"Four Weddings And A Funeral",
"Fountainhead, The",
"Fox and the Hound, The",
"The Fox and the Hound 2",
"Fracture",
"Frailty",
"Freaky Friday (2003 film)",
"Freddy Got Fingered",
"Freddy vs. Jason",
"Free Willy",
"French Connection, The",
"Frenzy",
"Friday",
"Friday Night Lights",
"Fried Green Tomatoes",
"Friendly Persuasion",
"Fritz the Cat",
"From Dusk till Dawn",
"From Hell",
"From Here to Eternity",
"From Russia with Love",
"Frost/Nixon",
"Fugitive, The",
"Full Metal Jacket",
"Galaxy Quest",
"Game, The",
"Game Plan, The",
"Gandhi",
"Gangs of New York",
"Garden State",
"Garfield",
"Gates of Heaven",
"Gattaca",
"Gentleman Prefer Blondes",
"George of the Jungle (film)",
"Georgia Rule",
"Get Carter",
"Gettysburg",
"Get Shorty",
"Ghostbusters",
"Ghost Dog: The Way of the Samurai",
"Ghost in the Shell 2: Innocence",
"Ghost Rider",
"G.I. Jane",
"Giant Claw, The",
"Girl, Interrupted",
"Girl Next Door, The",
"Girls Will Be Girls",
"Gladiator",
"Glen or Glenda",
"Glengarry Glen Ross",
"Glory",
"Glory Road",
"Godfather, The",
"Godfather, The: Part II",
"Godfather, The: Part III",
"Gods Must Be Crazy, The",
"Gone Baby Gone",
"Gone in 60 seconds",
"Gone with the Wind",
"Good Girl, The",
"Good Burger",
"Goodbye Girl, The",
"Good Bye Lenin!",
"Goodfellas",
"Good Luck Chuck",
"Good Morning, Vietnam",
"Good Night, and Good Luck.",
"Good Son, The",
"Good Will Hunting",
"Good Year, A",
"Good, the Bad and the Ugly, The",
"Goofy Movie, A",
"Goonies, The",
"Gotti",
"Graduate, The",
"Grand Hotel",
"Grand Voyage, Le",
"Grandma's Boy",
"Grapes of Wrath, The (1940)",
"Great Dictator, The",
"Great Expectations",
"Grease",
"Grease 2",
"Great Debaters, The",
"Great Escape, The",
"The Great Mouse Detective",
"The Great Outdoors",
"The Greatest Game Ever Played",
"Green for Danger",
"Green Mile, The",
"Green Zone",
"Gremlins",
"Grey Zone, The",
"Grindhouse",
"Groundhog Day",
"Grosse Pointe Blank",
"Grumpy Old Men",
"Guess Who",
"Guess Who's Coming to Dinner",
"Hackers",
"Hair",
"Halloween",
"Rob Zombie's Halloween",
"Halloween II (2009 film)",
"Half Baked",
"Hamlet 2",
"Hammett",
"Hancock",
"Hangover, The",
"Hannah and Her Sisters",
"Hannibal",
"Hannibal Rising",
"Happy Feet",
"Happy Gilmore",
"Hard Boiled",
"Hard Candy",
"Here Comes Pupcake",
"Hard Day's Night, A",
"Harold & Kumar Go to White Castle",
"Harold & Kumar Escape from Guantanamo Bay",
"Harold and Maude",
"Harry Potter and the Philosopher's Stone",
"Harry Potter and the Chamber of Secrets",
"Harry Potter and the Prisoner of Azkaban",
"Harry Potter and the Goblet of Fire",
"Harry Potter and the Order of the Phoenix",
"Harry Potter and the Half-Blood Prince (film)",
"Harry Potter and the Deathly Hallows: Part 1",
"Harvey",
"He's Just Not That Into You",
"He Died With A Felafel In His Hand",
"Heat",
"Heartbreak Ridge",
"Heathers",
"Heavy Traffic‎",
"Heavyweights",
"Hey Good Lookin'",
"Hellboy",
"Hellboy II: The Golden Army",
"Hellraiser",
"Hellbound: Hellraiser II",
"Hellraiser III: Hell on Earth",
"Hellraiser: Bloodline",
"Hellraiser: Inferno",
"Hellraiser: Hellseeker",
"Hellraiser: Deader",
"Hellraiser: Hellworld",
"Help!",
"Hercules (1997 film)",
"Hero",
"Hide and Seek",
"High Fidelity",
"High Noon",
"Highlander (series)",
"High School Musical",
"High School Musical 2",
"High School Musical 3",
"High Road To China",
"The Hills Have Eyes (2006 film)",
"His Girl Friday",
"History Boys, The",
"History of the World: Part I",
"History of Violence, A",
"Hitch",
"Hitchhiker's Guide to the Galaxy, The",
"Holes (film)",
"Holiday, The",
"Holiday Inn",
"Home Alone",
"Home Alone 2: Lost in New York",
"Homeward Bound II: Lost in San Francisco",
"Honey, I Shrunk The Kids",
"Hoodwinked",
"Hook",
"Hoosiers",
"Hospital, The",
"Hostel",
"Hostel: Part II",
"Hotel Rwanda",
"Hot Chick, The",
"Hot Fuzz",
"Hot Rod",
"Hot Shots! Part Deux",
"Hot Shots",
"Hours, The",
"The House Bunny",
"How the Grinch Stole Christmas! (1966 cartoon TV movie)",
"How the Grinch Stole Christmas (2000 live-action movie)",
"How to Lose a Guy in 10 Days",
"How to Train Your Dragon",
"Howard the Duck",
"Howl's Moving Castle",
"Howling, The",
"Hud",
"Hudsucker Proxy, The",
"Human Traffic",
"The Hunchback of Notre Dame (1996)",
"Hunt for Red October, The",
"Hurricane, The (1999)",
"Hurt Locker, The",
"Hustler, The",
"I Am Legend",
"I Am Sam",
"I Heart Huckabees",
"I Know What You Did Last Summer",
"I Love You, Man",
"I Now Pronounce You Chuck and Larry",
"I, Robot",
"I Still Know What You Did Last Summer",
"Ice Age",
"Ice Age: The Meltdown",
"Ice Age: Dawn of the Dinosaurs",
"Ice Princess",
"Ichigo Momomiya's Evolution",
"Idiocracy",
"If....",
"If Only",
"Ikiru",
"Il Postino",
"Illusionist, The",
"Imagine Me & You",
"I'm No Angel",
"I'm Not There",
"In & Out",
"In Bruges",
"In the Line of Fire",
"Incredible Hulk, The",
"In Her Shoes",
"In the Heat of the Night",
"Into the Blue",
"Inception",
"Incredibles, The",
"Inconvenient Truth, An",
"Independence Day",
"Inferno",
"Indiana Jones and the Kingdom of the Crystal Skull",
"Indiana Jones and the Last Crusade",
"Indiana Jones and the Temple of Doom",
"Innerspace",
"Inside Man",
"Inside Monkey Zetterland",
"Inspector Gadget",
"Inspector Gadget 2",
"Interview with the Vampire",
"Intolerable Cruelty",
"Invasion of the Body Snatchers (1956)",
"Invasion of the Body Snatchers (1978)",
"Inventing the Abbotts",
"Iron Man",
"Iron Man 2",
"Iron Giant, The",
"Iron Jawed Angels",
"Island, The",
"Island of Dr. Moreau, The (1996)",
"It's a Wonderful Life",
"It's a Mad, Mad, Mad, Mad World",
"It",
"It Happened One Night",
"Italian Job, The (1969)",
"Italian Job, The (2003)",
"Jack",
"Jacket, The",
"Jackie Brown",
"Jagged Edge",
"James and the Giant Peach",
"James Bond series",
"Jarhead",
"Jaws",
"Jaws 2 (1978 film)",
"Jaws 3-D",
"Jay and Silent Bob Strike Back",
"Jeepers Creepers",
"Jennifer's Body",
"Jeremiah Johnson",
"Jerk, The",
"Jerry Maguire",
"JFK",
"Joe's Apartment",
"Joe Dirt",
"Joe Versus the Volcano",
"Joseph: King of Dreams",
"Joshua Tree (1993 film)",
"Johnny Dangerously",
"Johnny English",
"John Tucker Must Die",
"Josie and the Pussycats",
"Jude",
"Judgment at Nuremberg",
"Jumanji",
"Jumper",
"Junebug",
"Jungle 2 Jungle",
"Jungle Book, The",
"Jungle Book 2, The",
"Jungle Book: Mowgli's Story",
"Juno",
"Jurassic Park",
"Jurassic Park: The Lost World",
"Jurassic Park 3",
"Just Friends",
"Just Like Heaven",
"Juwanna Mann",
"K-PAX",
"Kagemusha",
"Kalifornia",
"Kangaroo Jack",
"Karate Kid, The",
"Karate Kid, Part II, The",
"Karate Kid, Part III, The",
"Kate & Leopold",
"Kelly's Heroes",
"Kentucky Fried Movie, The",
"Key Largo",
"Khuda Kay Liye",
"Kicking & Screaming",
"Kicking and Screaming",
"Kill Bill: Volume 1",
"Kill Bill: Volume 2",
"Killer Klowns from Outer Space",
"Killers, The",
"Killing Fields, The",
"Kindergarten Cop",
"Kind Hearts and Coronets",
"King Arthur",
"King Kong (2005)",
"King of Comedy, The",
"King's Speech, The",
"Kingdom of Heaven",
"Kingpin",
"Kinsey",
"Kiss Before Dying, A",
"Kiss Kiss Bang Bang",
"Kiss Tomorrow Goodbye",
"Kite Runner, The",
"Klute",
"Knight's Tale, A",
"Knocked Up",
"Knute Rockne, All American",
"Kramer vs. Kramer",
"Kung Fu Hustle",
"Kung Fu Panda",
"Kung Fu Panda 2",
"L. A. Confidential",
"La lengua de las mariposas",
"Labyrinth",
"Ladder 49",
"Lady and the Tramp",
"Lady and the Tramp II: Scamp's Adventure",
"Ladies Man, The",
"Lady Eve, The",
"Lady from Shanghai, The",
"Land of the Dead",
"Lara Croft: Tomb Raider",
"Lara Croft Tomb Raider: The Cradle of Life",
"L. A. Story",
"Las Vegas",
"Last Boy Scout, The",
"Last Days of Disco, The",
"The Last House on the Left (2009 film)",
"Last Man on Earth, The",
"The Last Mimzy",
"Last of the Mohicans, The",
"Last Picture Show, The",
"Last Samurai, The",
"Last Starfighter, The",
"Laura",
"Latter Days",
"Lavender Hill Mob, The",
"Law Abiding Citizen",
"Lawrence of Arabia",
"Layer Cake",
"Legally Blonde",
"Legally Blonde 2: Red, White and Blonde",
"Lean on Me",
"League of Extraordinary Gentlemen, The",
"League of Their Own, A",
"Leaving Las Vegas",
"Legends of the Fall",
"Les Miserables",
"Legend of 1900, The",
"Legend of Zorro, The",
"Lemony Snicket's A Series of Unfortunate Events",
"Lenny",
"Léon",
"Leroy & Stitch",
"Lethal Weapon",
"Lethal Weapon 2",
"Lethal Weapon 3",
"Lethal Weapon 4",
"Letter, The",
"Letters from Iwo Jima",
"Letters to Juliet",
"Liar, Liar",
"Life",
"Life of Brian",
"Life Aquatic with Steve Zissou, The",
"Life of David Gale, The",
"Life or Something Like It",
"Life Is Beautiful",
"Lilo & Stitch",
"Lion King, The",
"Lion King II: Simba's Pride, The",
"Liquid Sky",
"Little Children",
"Little Giants",
"Little Mermaid, The",
"Little Mermaid II: Return to the Sea, The",
"Little Miss Sunshine",
"Little Nicky",
"Little Princess, A (BBC)",
"Little Rascals, The",
"Little Shop of Horrors, The",
"Live Free or Die Hard",
"Live and Let Die",
"Lock, Stock and Two Smoking Barrels",
"Lolita",
"Lone Star",
"Long Kiss Goodnight, The",
"Longest Day, The",
"Looney Tunes: Back in Action",
"Lord of the Rings: The Fellowship of the Ring, The",
"Lord of the Rings: The Return of the King, The",
"Lord of the Rings: The Two Towers, The",
"Lord of War",
"Lords of Dogtown",
"Loser",
"Lost Boys, The",
"Lost Highway",
"Lost Horizon",
"Lost in Space",
"Lost in Translation",
"Lost Weekend, The",
"Lot Like Love, A",
"Love Actually",
"Love Guru, The",
"Love Me If You Dare",
"Love Story",
"Loving Annabelle",
"Lucas",
"Lucky Number Slevin",
"M",
"Mad Max",
"Mad Max 2: The Road Warrior",
"Mad Max III: Beyond Thunderdome",
"Madagascar",
"Madagascar: Escape 2 Africa",
"Madea: Family Reunion",
"Magnificent Ambersons, The",
"Magnificent Seven, The",
"Magnolia",
"Major League",
"Major Payne",
"Malcolm X",
"Mallrats",
"Maltese Falcon, The",
"Man for All Seasons, A",
"Man of the Year",
"Man on Fire",
"Man in the Moon, The",
"Man on the Moon",
"Man Who Wasn't There, The",
"Man Who Shot Liberty Valance, The",
"Man with Two Brains, The",
"Manchurian Candidate, The (1962)",
"Manhattan",
"Manhattan Project, The",
"Mannequin",
"Manos: The Hands of Fate",
"Man Who Fell To Earth",
"Manhunter",
"Marnie",
"Mary Poppins (film)",
"MASH",
"Mask",
"Mask of Zorro, The",
"Master and Commander",
"Masters of the Universe",
"Match Point",
"Matewan",
"Matilda (film)",
"Matrix, The",
"Matrix Reloaded, The",
"Matrix Revolutions, The",
"Maverick",
"Max Keeble's Big Move",
"Max Payne",
"Me And You And Everyone We Know",
"Mean Girls",
"Mean Machine",
"Martin and Lewis",
"Meaning of Life, The",
"Meatballs",
"Meet Joe Black",
"Meet Me in St. Louis",
"Meet the Fockers",
"Meet the Parents",
"Meet the Robinsons",
"Meet the Spartans",
"Megamind",
"Melody (1971 film)",
"Memento",
"Memoirs of a Geisha",
"Me, Myself & Irene",
"Men of Honor",
"Men in Black",
"Men in Black II",
"The Men Who Stare At Goats",
"Messenger, The",
"Metropolitan",
"Miami Vice",
"Michael Clayton",
"Midnight Cowboy",
"Midsummer Night's Dream, A (1999)",
"Mighty Morphin Power Rangers: The Movie",
"Mighty Wind, A",
"Mike's New Car",
"Millers Crossing",
"Million Dollar Baby",
"Million Dollar Hotel, The",
"Milk",
"Minority Report",
"Miracle",
"Miracle on 34th Street",
"Mirrormask",
"Miss Congeniality",
"Miss Congeniality 2: Armed & Fabulous",
"Miss Pettigrew Lives for a Day",
"Missing",
"Mission: Impossible",
"Mission: Impossible II",
"Mission: Impossible III",
"Mississippi Burning",
"Mist, The",
"Mommie Dearest",
"Mona Lisa Smile",
"Money Pit, The",
"Money Talks",
"Mongol",
"Monsters, Inc.",
"Monsters vs. Aliens",
"Monty Python and the Holy Grail",
"Moon Child",
"Moonlight Mile",
"Moonstruck",
"Motorcycle Diaries, The",
"Moulin Rouge!",
"Mr. Brooks",
"Mr Death: The Rise & Fall of Fred A Leuchter Jr.",
"Mr. Deeds",
"Mr. Destiny",
"Mr. Mom",
"Mr. & Mrs. Smith",
"Mr. Smith Goes to Washington",
"Mrs. Doubtfire",
"Mrs. Miniver",
"Mulan",
"Mulholland Dr.",
"Mulholland Falls",
"Multiple Maniacs",
"Mummy, The",
"Mummy Returns, The",
"Music and Lyrics",
"Mutiny on the Bounty (1935)",
"Mutiny on the Bounty (1962)",
"My Best Friend's Wedding",
"My Big Fat Greek Wedding",
"My Blueberry Nights",
"My Cousin Vinny",
"My Dinner with Andre",
"My Fair Lady",
"My Favorite Year",
"My Girl",
"My Life Without Me",
"My Own Private Idaho",
"My Sassy Girl",
"Mystery Men",
"Nacho Libre",
"Nadja",
"Naked",
"Naked City, The",
"Naked Gun, The",
"Napoleon Dynamite",
"Narc",
"Nanny McPhee",
"Nashville",
"National Lampoon's Animal House",
"National Lampoon's Christmas Vacation",
"National Lampoon's European Vacation",
"National Lampoon's Vacation",
"National Lampoon's Vegas Vacation",
"National Treasure",
"National Treasure: Book of Secrets",
"Natural, The",
"Natural Born Killers",
"Nausicaä of the Valley of the Wind",
"Negotiator, The",
"Net, The",
"Network",
"Never Give a Sucker an Even Break",
"NeverEnding Story, The",
"New Jack City",
"New Moon (2009 film)",
"Newsies",
"Next Karate Kid, The",
"Nicholas & Alexandra",
"Nick and Norah's Infinite Playlist",
"Night at the Museum",
"Night at the Museum: Battle of the Smithsonian",
"Night at the Opera, A",
"Night at The Roxbury, A",
"Night of the Hunter, The",
"Night Shift",
"Nightmare Before Christmas, The",
"Nightmare on Elm Street, A",
"Nightmare on Elm Street 2: Freddy's Revenge, A",
"Nightmare on Elm Street 3: Dream Warriors, A",
"Nightmare on Elm Street 4: The Dream Master, A",
"Nim's Island",
"Nine Lives of Fritz the Cat, The",
"Nine to Five",
"Ninotchka",
"No Country for Old Men",
"No Way Out",
"Nobody's Fool",
"Norbit",
"North by Northwest",
"Not Another Teen Movie",
"Notebook, The",
"Nosferatu",
"Notes on a Scandal",
"Nothing to Lose",
"Notorious",
"Notting Hill",
"Number 23, The",
"Nutty Professor 2",
"O Brother, Where Art Thou?",
"Ocean's Eleven (2001)",
"Ocean's Thirteen",
"Ocean's Twelve",
"Office Space",
"Officer and a Gentleman, An",
"Oklahoma! (1955)",
"Oldboy",
"Old School",
"Oliver & Company",
"Omega Man, The",
"Omen, The",
"Omen, The (2006)",
"Omkara",
"On Golden Pond",
"On Her Majesty's Secret Service",
"On Moonlight Bay",
"Once Upon a Time in America",
"Once Upon a Time in Mexico",
"Once Upon a Time in the West",
"Once Were Warriors",
"One Flew Over the Cuckoo's Nest",
"One Hundred and One Dalmatians",
"One Magic Christmas",
"Open Season",
"Open Season 2",
"Opening of Misty Beethoven, The",
"Operation Dumbo Drop",
"Orgazmo",
"Original Sin",
"Osmosis Jones",
"Out of Sight",
"Out of the Past",
"Outbreak",
"Outlaw Josey Wales, The",
"Outside Providence",
"Over the Hedge",
"The Pacifier",
"Pagemaster, The",
"Paparazzi",
"Paper Chase, The",
"Paradine Case, The",
"Parallax View, The",
"Parenthood",
"Party, The",
"Party Monster",
"Passion of the Christ, The",
"Patch Adams",
"Paths of Glory",
"Patriot Games",
"Patton",
"Paul Blart: Mall Cop",
"Pay It Forward",
"Paycheck",
"PCU",
"Peaceful Warrior",
"Peacemaker, The",
"Pee-wee's Big Adventure",
"Pelican Brief, The",
"Penelope (2008 film)",
"People vs. Larry Flynt, The",
"Perfect Storm, The",
"Peter Pan (1953)",
"Peter Pan (2003)",
"Phantom of the Opera, The (2004)",
"Phantom of the Paradise",
"Philadelphia",
"Philadelphia Story, The (1940)",
"Pi",
"Piano, The",
"Pillow Talk",
"Pineapple Express",
"Pink Floyd The Wall",
"Pink Flamingos",
"Pink Panther Strikes Again, The",
"Pinocchio (1940 film)",
"Pirate Movie, The",
"Pirates of Penzance, The",
"Pirates of the Caribbean: At World's End",
"Pirates of the Caribbean: Dead Man's Chest",
"Pirates of the Caribbean: The Curse of the Black Pearl",
"Pirate Radio (a.k.a. The Boat That Rocked)",
"Pirates Who Don't Do Anything: A VeggieTales Movie, The",
"Pitch Black",
"Plan 9 from Outer Space",
"Planes, Trains, and Automobiles",
"Planet of the Apes (1968)",
"Platoon",
"Playing By Heart",
"Pleasantville",
"Pocahontas",
"Point Break",
"Polar Express, The",
"Police Academy",
"Poltergeist",
"Polyester",
"Pooh's Grand Adventure: The Search for Christopher Robin",
"Pooh's Heffalump Movie",
"Pootie Tang",
"Popeye",
"Porco Rosso",
"Poseidon",
"Poseidon Adventure, The",
"Postman Always Rings Twice, The",
"Powder",
"Practical Magic",
"Predator",
"Predator 2",
"Prestige, The",
"Pretty in Pink",
"Pretty Woman",
"Pride",
"Pride and Prejudice (2005)",
"Primal Fear",
"Prince of Egypt, The",
"Prince of Persia: The Sands of Time (film)",
"The Princess and the Frog",
"Princess Bride, The",
"Princess Diaries, The",
"Princess Diaries 2, The: Royal Engagement",
"Princess Mononoke",
"Private Parts",
"Producers, The (1968)",
"Producers, The (2005)",
"Proposition, The",
"Prozac Nation",
"Pursuit of Happyness, The",
"Psycho (1960)",
"Psycho II",
"Psycho III",
"Psycho (1998)",
"Public Enemies",
"Pulp Fiction",
"Punisher, The",
"Punisher: War Zone",
"Quadrophenia",
"Quarantine",
"Queen, The",
"Queen of the Damned",
"Quest for Camelot",
"Quiet Man, The",
"Quills",
"Quantum of Solace",
"Rabbit-Proof Fence",
"Racing Stripes",
"Rage: Carrie 2, The",
"Raging Bull",
"Raiders of the Lost Ark",
"Rain Man",
"Rainmaker, The (1997)",
"Raising Arizona",
"Raising Helen",
"Ramayana: The Legend of Prince Rama",
"Rambo: First Blood Part II",
"Rambo III",
"Rapture, The",
"Rat Race",
"Ratatouille",
"Ray",
"Razor's Edge, The",
"Real Genius",
"Reality Bites",
"Rear Window",
"Rebecca",
"Rebel Without a Cause",
"Rebound",
"REC 2",
"Red Eye",
"Red Dawn",
"Red Dragon",
"Red River",
"Red Shoes, The",
"Reefer Madness‎",
"Reign of Fire",
"Reign Over Me",
"Religulous",
"Remember the Titans",
"Remo Williams: The Adventure Begins",
"Rent",
"Replacements, The",
"Repo! The Genetic Opera",
"Repo Man",
"Requiem for a Dream",
"The Rescuers",
"Reservoir Dogs",
"Resident Evil",
"Resident Evil: Apocalypse",
"Return of Jafar, The",
"Return to Never Land",
"Return to the Blue Lagoon",
"Reversal of Fortune",
"Revolver",
"Riding the Bus with My Sister",
"Ring, The",
"Ring Two, The",
"Rising Sun",
"Risky Business",
"Ritz, The",
"River Runs Through It, A",
"Road, The",
"Road House",
"Road to El Dorado, The",
"Road to Perdition",
"Robin Hood (1973)",
"Robin Hood: Men in Tights",
"Robin Hood: Prince of Thieves",
"RoboCop",
"Robot Monster",
"Robots",
"Rock & Rule",
"Rock, The",
"RockNRolla",
"Rocky",
"Rocky II",
"Rocky III",
"Rocky IV",
"Rocky V",
"Rocky Balboa",
"Rocky Horror Picture Show, The",
"Role Models",
"Roman Holiday",
"Romeo Must Die",
"Romy and Michele's High School Reunion",
"Rosencrantz & Guildenstern Are Dead",
"Rosemary's Baby",
"Rounders",
"Royal Tenenbaums, The",
"Roxanne",
"Rudy",
"The Rugrats Movie",
"Rugrats in Paris: The Movie",
"Rugrats Go Wild",
"Runaway Bride",
"Rundown, The",
"Rush Hour",
"Rush Hour 2",
"Rush Hour 3",
"Rushmore",
"RV",
"S Club Seeing Double",
"Saboteur",
"Sahara",
"Samurai X",
"Sandlot, The",
"Santa Claus: The Movie",
"Santa Clause, The",
"Saturday Night Fever",
"Savages, The",
"Saved",
"Save the Last Dance",
"Saving Private Ryan",
"Saving Silverman",
"Saw",
"Saw II",
"Saw III",
"Saw IV",
"Saw V",
"Saw VI",
"Saw 3D",
"Scarface",
"Scary Movie",
"Scary Movie 2",
"Scary Movie 3",
"Scary Movie 4",
"Scent of a Woman",
"Schindler's List",
"School of Rock",
"Science of Sleep, The",
"Scooby-Doo",
"Scoop",
"Scott Pilgrim vs. the World",
"Scream",
"Scream 2",
"Scream 3",
"Scream 4",
"Scrooged",
"Secondhand Lions",
"The Secret (film)",
"The Secret Garden (1993 film)",
"The Secret of NIMH",
"Secret Window",
"Semi-Pro",
"Sense and Sensibility",
"Serendipity",
"Serenity",
"Serial Mom",
"Se7en",
"The Seven Samurai",
"The Seventh Seal",
"Sex and the City: The Movie",
"Sex Drive",
"Shadowlands",
"Shaggy Dog, The",
"Shakespeare in Love",
"Shallow Hal",
"Shark Tale",
"Shaun of the Dead",
"Shawshank Redemption, The",
"She's All That",
"She-Devil",
"She Done Him Wrong",
"Sherlock Holmes (2009 film)",
"She's Out of My League",
"She's the Man",
"Shining, The",
"Sholay",
"Shoot 'Em Up",
"Short Circuit",
"Shot in the Dark, A",
"Shrek",
"Shrek 2",
"Shrek Forever After",
"Shrek the Third",
"Signs",
"Silence of the Lambs, The",
"Simon Birch",
"Simpsons Movie, The",
"Sin City",
"Singin' in the Rain",
"Sixteen Candles",
"The Sixth Sense",
"Sky Captain and the World of Tomorrow",
"Sky High",
"Slap Her She's French",
"Slap Shot",
"Sleeping Beauty",
"Sleepless in Seattle",
"Sleepy Hollow",
"Slumdog Millionaire",
"Sling Blade",
"Small Soldiers",
"Smokin' Aces",
"Snatch",
"Snoopy, Come Home",
"Snow Dogs",
"Snow White and the Seven Dwarfs (1937 film)",
"So I Married an Axe Murderer",
"Sometimes in April",
"Somewhere in Time",
"Songwriter",
"Sons of Eilaboun, the",
"Sophie's choice",
"The Sorcerer's Apprentice (2010 film)",
"Soul Plane",
"Soylent Green",
"Sound of Music, The",
"Southland Tales",
"Spaceballs",
"Space Chimps",
"Spartacus",
"Speed",
"Speed 2: Cruise Control",
"Spider-Man (film)",
"Spider-Man 2",
"Spider-Man 3",
"Spirit: Stallion of the Cimarron",
"Splash",
"The SpongeBob SquarePants Movie",
"Spy Hard",
"Stage Fright",
"Stagecoach (1939)",
"Stand and Deliver",
"Stand By Me",
"Stardust",
"Star Trek",
"Star Trek: The Motion Picture",
"Star Trek II: The Wrath of Khan",
"Star Trek III: The Search for Spock",
"Star Trek IV: The Voyage Home",
"Star Trek V: The Final Frontier",
"Star Trek VI: The Undiscovered Country",
"Star Trek Generations",
"Star Trek: First Contact",
"Star Trek: Insurrection",
"Star Trek Nemesis",
"Star Wars Episode I: The Phantom Menace",
"Star Wars Episode II: Attack of the Clones",
"Star Wars Episode III: Revenge of the Sith",
"Star Wars Episode IV: A New Hope",
"Star Wars Episode V: The Empire Strikes Back",
"Star Wars Episode VI: Return of the Jedi",
"Star Wars: The Clone Wars (film)",
"Starship Troopers",
"Starsky and Hutch",
"Stay Alive",
"Staying Alive",
"Steel Magnolias",
"Step Brothers",
"Step Up",
"The Stepfather (2009 film)",
"Stewie Griffin: The Untold Story",
"The Sting",
"Strange Brew",
"Strange Days",
"Stranger than Fiction",
"Stripes",
"Striptease",
"Sunshine",
"Superman Returns",
"Super Mario Bros. (film)",
"Super Troopers",
"Superbad",
"Superhero Movie",
"Superstar",
"Surf II",
"Surf's Up",
"Surrogates (film)",
"Suspicion",
"Sweeney Todd: The Demon Barber of Fleet Street",
"Sweetest Thing, The",
"Sweet Home Alabama",
"Swimming with Sharks",
"Sinatra",
"Swingers",
"Swordfish",
"The Sword in the Stone (film)",
"Sydney White",
"Tall Tale",
"Talladega Nights: The Ballad of Ricky Bobby",
"Tamara (2005 film)",
"Tangled",
"Tao of Steve, The",
"Tarzan (1999 film)",
"Tarzan II",
"Taxi",
"Taxi Driver",
"Teachers",
"Team America: World Police",
"Tears of the Black Tiger",
"Teenage Mutant Ninja Turtles",
"Teenage Mutant Ninja Turtles II: The Secret of the Ooze",
"Teenage Mutant Ninja Turtles III",
"Tenacious D in The Pick of Destiny",
"Terms of Endearment",
"Terminal, The",
"Terminator, The",
"Terminator 2: Judgment Day",
"Terminator 3: Rise of the Machines",
"Terminator Salvation",
"Texas Chain Saw Massacre, The",
"The Texas Chainsaw Massacre (2003)",
"The Texas Chainsaw Massacre: The Beginning",
"Thank You for Smoking",
"Thelma & Louise",
"There Will Be Blood",
"There's Something About Mary",
"The Mirror Has Two Faces",
"Thin Man, The",
"Thin Red Line, The (1998)",
"Thing, The",
"Thing From Another World, The",
"Thirteen",
"Thirteen Days",
"This is Spinal Tap",
"Thomas Crown Affair, The",
"Thor (film)",
"Thousand Clowns, A",
"Three Amigos",
"Three Days of the Condor",
"The Blob",
"The Ten Commandments",
"Three Little Pigs",
"Three Musketeers, The (1948)",
"Three Musketeers, The (1973)",
"Three Musketeers, The (1993)",
"The secret of their eyes",
"Thumbsucker",
"Thunderbolt and Lightfoot",
"THX 1138",
"Time Machine",
"Tin Cup",
"Titan AE",
"Titanic",
"Titanic (1953 film)",
"TMNT",
"To Catch a Thief",
"To Have and Have Not",
"To Kill a Mockingbird",
"Tombstone",
"Tomb Raider",
"Tommy Boy",
"Tomorrow Never Dies",
"Tootsie",
"Top Gun",
"Top Secret",
"Topaz",
"Total Recall",
"Towering Inferno, The",
"Toxic Avenger, The",
"Toy Story",
"Toy Story 2",
"Toy Story 3",
"Trading Places",
"Traffic",
"Training Day",
"Trainspotting",
"Transamerica",
"Transformers (2007)",
"Transformers: Revenge of the Fallen",
"Transformers: The Movie, The",
"Treasure of the Sierra Madre, The",
"Treasure Planet",
"Tremors",
"Trick 'r Treat",
"Tristan and Isolde",
"Trixie",
"Troll",
"A Troll in Central Park",
"Tron",
"Tropic Thunder",
"Troy",
"True Grit (1969 film)",
"True Grit (2010 film)",
"True Lies",
"True Romance",
"Truman Show, The",
"Tuck Everlasting (2002 film)",
"Twelve Monkeys",
"Twilight",
"The Twilight Saga: Eclipse",
"The Twilight Saga: New Moon",
"Twister",
"Two Moon Junction",
"Two Weeks Notice",
"UHF",
"Ultraviolet",
"Unaccompanied Minors",
"Unbreakable",
"Uncle Buck",
"Under Siege",
"Underdog",
"Underworld: Evolution",
"Underworld: Rise of the Lycans",
"Unforgiven",
"Universal Soldier",
"United States of Leland, The",
"Untouchables, The",
"Up",
"Up in the Air",
"Uptown Girls",
"Urban Cowboy",
"Urban Legend",
"U.S. Marshals",
"Usual Suspects, The",
"V for Vendetta",
"Valkyrie",
"Vampires Suck",
"Van Helsing",
"Van Wilder",
"Vanilla Sky",
"Vampire in Brooklyn",
"Varsity Blues",
"Velvet Goldmine",
"Versus",
"VeggieTales: Gideon Tuba Warrior",
"VeggieTales: Moe and the Big Exit",
"VeggieTales: Tomato Sawyer and Huckleberry Larry's Big River Rescue",
"Vertigo",
"Victor/Victoria",
"Vicky Cristina Barcelona",
"Videodrome",
"Village, The",
"Virgin Suicides, The",
"Volcano",
"Wag the Dog",
"Waiting for Guffman",
"Waking Life",
"Waiting...",
"Waitress",
"Walk Hard: The Dewey Cox Story",
"Walk the Line",
"Walk to Remember, A",
"WALL-E",
"Wall Street",
"Wallace & Gromit in The Curse of the Were-Rabbit",
"War and Peace",
"War, Inc.",
"War of the Worlds, The (1953)",
"War of the Worlds (2005)",
"WarGames",
"Warriors, The",
"Watcher, The",
"Watchmen",
"Waterboy, The",
"Wayne's World",
"Wayne's World 2",
"Way of the Gun, The",
"We Were Soldiers",
"Weather Man, The",
"Wedding Crashers",
"Wedding Date, The",
"Wedding Planner, The",
"Wedding Singer, The",
"Weird Science",
"West Side Story",
"Wet Hot American Summer",
"Whale Rider",
"What a Girl Wants",
"What About Bob?",
"What Dreams May Come",
"What Ever Happened to Baby Jane?",
"What Happens in Vegas",
"What Lies Beneath",
"What's Up, Doc?",
"When a Stranger Calls (2006 film)",
"When Harry Met Sally...",
"While You Were Sleeping",
"White Men Can't Jump",
"Who Framed Roger Rabbit",
"Who's Afraid of Virginia Woolf?",
"Whole Nine Yards, The",
"Wild Bunch, The",
"Wicker Man, The (1973)",
"Wicker Man, The (2006)",
"Wicker Park",
"Wild at Heart",
"Wild Hogs",
"Willow",
"Willy Wonka & the Chocolate Factory",
"Windtalkers",
"Wings of Desire",
"Winter's Bone",
"Wishmaster",
"Wishmaster 2: Evil Never Dies",
"Withnail and I",
"Without a Paddle",
"Witness",
"The Wizard of Oz",
"Wolf Man, The",
"Working Girl",
"World Is Not Enough, The",
"World's Fastest Indian, The",
"Wrestler, The",
"Wristcutters: A Love Story",
"Written on the Wind",
"Wyatt Earp",
"X Files: I Want to Believe, The",
"X Files: Fight The Future, The",
"X-Men",
"X2 (X-men 2)",
"X-Men: First Class (film)",
"X-men: The Last Stand",
"X-Men Origins: Wolverine",
"Xanadu",
"xXx",
"Yankee Doodle Dandy‎",
"Year One",
"Yellow Submarine",
"Yes Man",
"Yojimbo",
"You Don't Mess with the Zohan",
"You Got Served",
"You, Me and Dupree",
"You Only Live Twice",
"Young and Innocent",
"Young Frankenstein",
"Young Guns",
"Young Guns II",
"Young Mr. Lincoln",
"Young Rajah, The",
"Your Friend the Rat (short)",
"Yours, Mine and Ours (1968 film)",
"Yours, Mine and Ours (2005 film)",
"You've Got Mail",
"Zack and Miri Make a Porno",
"Zardoz",
"Zed & Two Noughts, A",
"Zelig",
"Zeitgeist: The Movie",
"Zenon: Girl of the 21st Century",
"Zodiac",
"Zombieland",
"Zoolander",
"Zorro, The Gay Blade",
"Zulu",
"Zathura",
"100 Days (1991)",
"100 Days (2001)",
"10,000 BC",
"11th Hour, The",
"13 Moons",
"15 Minutes",
"16 Years of Alcohol",
"187 (film)",
"18000 Dead in Gordon Head",
"24 (film)",
"28 Weeks Later",
"2046",
"3 O'Clock High",
"30 Days of Night",
"5 centimeters per second",
"5x2",
"51st State, The",
"55 Days at Peking",
"7 Samurai",
"7 Years In Tibet",
"84 Charing Cross Road",
"88 Minutes",
"800 Bullets",
"61*",
"9 (film)",
"99 franks",
"300 Pound Beauty",
"A Bridge Too Far",
"About Last Night...",
"Accidental Spy, The",
"Actors, The",
"Addicted to Love",
"Adventures of Don Juan, The",
"Adventures of Ichabod and Mr. Toad, The",
"Adventures of Milo and Otis, The",
"Afterglow",
"After Sex",
"Against the Ropes",
"Akaler Sandhane (a.k.a. In Search of Famine)",
"Akira",
"Alamo, The",
"Albino Alligator",
"Alexandra's Project",
"Alias Betty",
"Alien Autopsy",
"Alien Nation",
"Alien Resurrection",
"Aliens of the Deep",
"All About My Mother",
"All About the Benjamins",
"All or Nothing",
"All the Pretty Horses",
"All the Queen's Men",
"All the Real Girls",
"Almost Peaceful",
"Alone in the Dark",
"Alucarda",
"Amati Girls, The",
"Amazing Grace",
"American Astronaut, The",
"American Pie 5 Naked Mile",
"American Pie: Band Camp",
"American Pie: Beta House",
"Americanization of Emily, The",
"American Yakuza",
"Amistad",
"An American Rhapsody",
"Andre (film)",
"Angel-A",
"Another Gay Movie",
"Antwone Fisher",
"Any Way the Wind Blows",
"Apartment Zero",
"Arabian Knight (aka The Thief and the Cobbler)",
"Artists and Models",
"Around the World in 80 Days (film)",
"As It Is in Heaven",
"Astronaut Farmer, The",
"Athadu",
"Attack On Leningrad",
"Autumn in New York",
"Babe: Pig in the City",
"Babyboy",
"Baby Boom",
"Baby Mama",
"Baltimore Bullet, The",
"Basketball Diaries",
"Barnyard",
"Battle Beyond the Stars",
"Beaches",
"Bean (1997 film)",
"Beautician And The Beast, The",
"Beautiful People",
"Beaver Trilogy, The",
"Because I Said So",
"Because of Winn-Dixie",
"Be Cool",
"Before Night Falls",
"Behind the Red Door",
"Believer, the",
"Best Little Whorehouse in Texas, The",
"Better Luck Tomorrow",
"Beyond the Gates",
"Better Tomorrow II, A",
"Better Tomorrow III, A",
"Bewitched",
"Big Kahuna, The",
"Big Money Hustlas",
"Big Shot's Funeral",
"Big Bounce, The",
"Bigger Than Life",
"Bill and Ted's Bogus Journey",
"Billy Elliot",
"Bio-Dome",
"Birthday Girl",
"Bitter Victory",
"Black Cauldron, The",
"Black Chicks Talking",
"Black Hole, The",
"Black Snake Moan",
"Black Stallion, The",
"Blame It on Rio",
"Bless the Child (2000)",
"Bless the Child (2003)",
"Blind Beast vs. Dwarf",
"Blood and Chocolate",
"Blood In Blood Out",
"Blood of Hussain, The",
"Blood Rayne 2 Deliverence",
"Bloodsport",
"Blue Car",
"Blue Diner, The",
"Blue Hill Avenue",
"Blue Streak",
"Bobby",
"Bon Cop, Bad Cop",
"Bone Collector, The",
"Born to Be Bad (1934)",
"Born to Be Bad (1950)",
"Bottle Shock",
"Bounty Hunter, The (1954)",
"Bounty Hunter, The (2010)",
"Boys from Brazil",
"Brain Dead",
"Brave Little Toaster, The",
"Bread and Milk",
"Breakfast of Champions",
"Break-Up, The",
"Breed, The (2001)",
"Breed, The (2006)",
"Briana Loves Jenna",
"Bride & Prejudice",
"Bride of the Wind",
"Bridge Too Far, A",
"Brief Crossing",
"Brigham City",
"Bright Young Things",
"Bring Me the Head of Alfredo Garcia",
"Bring It On II",
"Brink!",
"Brokedown Palace",
"Bronco Billy",
"Bronx Tale, A",
"Brother",
"Brotherhood of the Wolf",
"Brothers Grimm, The",
"Brown Sugar",
"Brylcreem Boys, The",
"Buffalo Soldier",
"Buying the Cow",
"Cadillac Records",
"Cake Eaters, The",
"Camp",
"Can't Hardly Wait",
"Cannibal! The Musical",
"Captain America: The First Avenger",
"Carbon Copy",
"Carpool",
"Carry On Series, The",
"Cat in the Hat, The",
"Catch That Kid",
"Cats Don't Dance",
"Cat's Meow, The",
"Center Stage",
"Chairman of the Board",
"Chances Are",
"Chandni Bar",
"Changeling (2008)",
"Charly",
"Chaos",
"Cheaper By The Dozen 2",
"Cheats",
"Cheech & Chong's Next Movie",
"Chicken Little",
"Chisum",
"Chopper",
"Christmas Vacation",
"Cincinnati Kid, The",
"City Slickers II",
"Cinderella Man",
"Clash of the Titans",
"Clean and Sober",
"Cobra",
"College Road Trip",
"CONTROL",
"Conversations with My Gardener",
"Confessions of a Teenage Drama Queen",
"Confessions of Shopaholic",
"Cop and a Half",
"Court Jester, The",
"Counterfeiters, The",
"Courage Under Fire",
"Covenant, The",
"C.R.A.Z.Y.",
"Crew, The",
"Crocodile Dundee II",
"Crocodile Dundee in Los Angeles",
"Crow, The: City Of Angels",
"Crow, The: Salvation",
"Crow, The: Wicked Prayer",
"Curious George",
"Cutthroat Island",
"Cypher",
"Daddy's Little Girls",
"Dancer In The Dark",
"Dangerous Minds",
"Danny The Dog",
"Darling Lili",
"D.A.R.Y.L.",
"Date Night",
"Day at the Races, A",
"Day the Earth Stood Still, The",
"Daylight",
"Days of Being Wild",
"Dead Man",
"Dead Man Walking",
"Dear John",
"Dead Men Don't Wear Plaid",
"Death Note The Last Name",
"Death in Venice",
"Death Proof",
"Death Race 2000",
"Deep Blue Sea",
"Deep Cover",
"Defiance (1980)",
"Defiance (2008)",
"Definitely, Maybe",
"Dennis the Menace",
"Desk Set",
"Desparado",
"Desperate Hours",
"Diary of a Mad Black Woman",
"Die you Zombie Bastards",
"Diggstown",
"Dil Chahta Hai",
"Dinner at Eight",
"Dirty Deeds",
"Dirty Love",
"Dirty Work",
"Dogtown and Z Boys",
"Dolores Claiborne",
"Domino",
"Don't Eat the Pictures",
"Doom Generation, The",
"Downfall",
"Drag Me to Hell",
"Dragonfly",
"Dragon Hunters (2008 film)",
"Dream for an Insomniac",
"Drillbit Taylor",
"Drugstore Cowboy",
"Duke and the Great Pie War",
"Duma",
"Easter Carol, An",
"Eating Raoul",
"Eight Below",
"El Cid",
"Election",
"Elektra",
"Elephant Man, The",
"Elkton Chronicles, The",
"Ellie Parker",
"Employee of the Month",
"Endangered Species (1982)",
"Endangered Species (2002)",
"Enough",
"Ernest Goes to Africa",
"Ernest Goes to School",
"Ernest in the Army",
"Ernest Rides Again",
"Escape from Mars",
"Escape to Athena",
"Equinox (1970)",
"Equinox (1992)",
"Everything you always wanted to know about sex * but were afraid to ask",
"eXistenZ",
"Exit Sunset Boulevard",
"Eye, The",
"Evening",
"Eyewitness (1956)",
"Eyewitness (1970)",
"Eyewitness (1981)",
"Eyewitness (1999)",
"Fabulous Baker Boys, The",
"Fair Game",
"Family Stone, The",
"Fanboys",
"Far and Away",
"Far from Home: The Adventures of Yellow Dog",
"Fearless",
"Feast of Love",
"Felidae",
"Fido",
"Fighting",
"Fighting Temptations, The",
"Fille Sur Le Pont, La",
"Final Destination 5",
"Firehouse Dog",
"Fireproof",
"Fired UP!",
"First Daughter",
"First Sunday",
"Five People You Meet In Heaven, The",
"Flags of Our Fathers",
"Flesh and Bone",
"Flipper (1963)",
"Flipper (1996)",
"Flipper's New Adventure",
"Fluke",
"Flying Leathernecks",
"Fool's Gold",
"Foot Fist Way, The",
"For Love or Money",
"Forget Paris",
"Fort Apache, The Bronx",
"Fortress",
"Fountain, The",
"Frankenstein (1931)",
"Freaks",
"Fred Claus",
"Freedom Writers",
"French Connection, The",
"French Kiss",
"Fresh Horses",
"Frighteners, The",
"Friends with Money",
"From Justin to Kelly",
"Funny Face",
"Find me guilty",
"From Paris,With love",
"G-Force",
"Gaslight (1944)",
"Gathering, The",
"General's Daughter, The",
"George of the Jungle",
"Get rich or die trying",
"Ghost World",
"Giant",
"Glitters",
"Gods and Monsters",
"Gods must be Crazy",
"Goal",
"Gone Fishin'",
"Good Advice",
"Good Night, The",
"Go West",
"Goldfish Memory",
"Graduation Day",
"Grand, The",
"Great Sinner, The",
"Great White Hype, The",
"Green Hornet, The",
"Green Lantern, The",
"Green Street Hooligans",
"Grind",
"Grizzly Man",
"Grudge, The",
"Grudge 2, The",
"Grumpier Old Men",
"Guardian, The",
"Gunmen",
"Guru, The",
"Hamburger Hill",
"Happily N'ever After",
"Happy Go Lucky",
"Hard Ball",
"Harry & Son",
"Harry and Tonto",
"Hating Alison Ashley",
"Hawaii",
"Heaven's Gate",
"Heavy Metal",
"Head of State",
"Heist",
"Hell Ride",
"Herbie Fully Loaded",
"Herbie Goes Bananas",
"Herbie Goes to Monte Carlo",
"Herbie Rides Again",
"Her Minor Thing",
"Hidalgo",
"Highway",
"The Hills Have Eyes",
"The Hills Have Eyes Part II",
"The Hills Have Eyes 2",
"The Hitcher (2007 film)",
"Hitler the rise of evil",
"Hollow Man",
"Hollow Man 2",
"Home Alone 3",
"Home Alone 4",
"Homeward Bound: The Incredible Journey",
"Home for the Holidays",
"Honey",
"Honeymoon in Vegas",
"Hoodwinked 2: Hood Vs. Evil",
"Hoot",
"Horton Hears a Who",
"Hot Blood",
"Hotel Manor Inn, The",
"Hot Pursuit",
"House of Fools",
"House on Haunted Hill (1999)",
"How to Get Ahead in Advertising",
"How to Steal a Million",
"Huitième jour, Le",
"Hulk",
"Hurlyburly",
"Hustle & Flow",
"Heavenly Forest",
"Hannah Montana: The Movie",
"I Dreamed of Africa",
"I Know Who Killed Me",
"I Think I Love My Wife",
"I Was a Teenage Zombie",
"Identity (2003)",
"Igby Goes Down",
"Illegally Yours",
"Indian Runner, The",
"Internal Affairs",
"Intermission",
"Interstate 60",
"Intimate Relations (1953)",
"Intimate Relations (1996)",
"Inglorious Basterds",
"Into The Wild",
"In a Lonely Place",
"In Good Company (2000)",
"In Good Company (2004)",
"In the Land of Women",
"In the Loop",
"In the Mood for Love",
"In the Mouth of Madness",
"Investigating Sex",
"Invisible Man (1933)",
"Invictus (2009)",
"Immortal Beloved",
"I.Q.",
"I Want Candy",
"Invincible (2006)",
"Irreconcilable Differences",
"Jackal, The",
"Jackass",
"Jackass 2",
"Jacob Have I Loved",
"Jacob's Ladder",
"Jade",
"Jailbait with Michael Pitt",
"Jane Eyre (1944 film)",
"Jane Eyre (1996 film)",
"Jane Eyre (1997 film)",
"Jaws: The Revenge",
"Jason T. Conrad and Friends: Viking-Sized Adventures",
"Jonah: A VeggieTales Movie",
"John Q",
"Johnny Guitar",
"Johnny Mnemonic",
"Joy division (2006)",
"Jumpin' Jack Flash",
"Just Married",
"Just Visiting",
"Just Go With It",
"Just My Luck",
"Kids in America",
"Keith",
"Killer, The",
"King of Kings",
"King Kong (1933)",
"Kingdom, The",
"Kiss Me Deadly",
"Knight and Day",
"Krippendorf's Tribe",
"Kid, The",
"Kung Pow: Enter The Fist",
"Knock on Any Door",
"Knocking on the Heaven's Door",
"Knowing",
"Lackawanna Blues",
"Lady in the Water",
"Lagaan",
"Last Action Hero",
"Last Detail, The",
"The Last Kiss",
"Last Producer, The",
"Late Night Shopping",
"Leatherface: Texas Chainsaw Massacre III",
"Leatherheads",
"Leaving Normal",
"Legend of the Lone Ranger, The",
"Leiutajateküla Lotte",
"Lemon Drop Kid, The",
"Lesbian Vampire Killers",
"Let Me In",
"Libertine, The",
"Life and Times of Judge Roy Bean, The",
"Lightning Over Water",
"Lilo & Stitch 2: Stitch has a Glitch",
"Lion in Winter, The",
"Lion King 1 1/2, The",
"Limey, The",
"Lion of the Desert",
"Lions For Lambs",
"Little Big Man",
"Little Black Book",
"Little Manhattan",
"Little Women (1994)",
"Local Hero",
"Long Goodbye, The",
"Lookout, The",
"Lost and Found",
"Love and Death",
"Love at Large",
"Love Bug, The",
"Love, Honour and Obey",
"Love in the afternoon",
"Love Jones",
"Love Song for Bobby Long, A",
"Love the Hard Way",
"Love Stinks",
"Lemonade Mouth 2011",
"Lusty Men, The",
"Machinist, The",
"Mackintosh Man, The",
"Made",
"Made in Britain",
"Madea: Diary of a Mad Black Woman",
"Majestic, The",
"Malena",
"Malev",
"Mamma Mia! (film)",
"Man Apart, A",
"Man in the Iron Mask, The",
"Manic",
"Many Adventures of Winnie the Pooh, The",
"Marie",
"Marie Antoinette (2006 film)",
"Marked for Death",
"Marley And Me",
"Martian Child",
"Mary and Max",
"Maid in Manhattan",
"Mean Streets",
"Meet Bill",
"Meet the Browns",
"Meet the Feebles",
"Mehed ei nuta",
"Men in Black III",
"Menace 2 Society",
"Message in a bottle",
"Midnight Express",
"Million Dollar Baby (1941)",
"Millions",
"Misery",
"Mission, The",
"Mission Impossible IV",
"Mission to Mars",
"Modern Problems",
"Mom's Got A Date With A Vampire",
"Mortal Thoughts",
"Mr. 3000",
"Mr. Bean's Holiday",
"Monster's Ball",
"Mr. Holland's Opus",
"Mrs. Parker and the Vicious Circle",
"Ms. 45 (a.k.a. Angel of Vengeance)",
"Muse, The",
"Munich",
"Murder on the Orient Express",
"Murderball",
"Murder Live",
"Music Man,The",
"Mutual Appreciation",
"My Dog Skip",
"My First Mister",
"Mystic Pizza",
"Nativity Story, The",
"Never Back Down",
"Never Been Kissed",
"Nancy Drew",
"National Lampoon's Senior Trip",
"Naughy Nineties, The",
"Never Cry Wolf",
"New Guy, The",
"New World, The",
"NEXT",
"New York Minute",
"Next Friday",
"Next Stop Wonderland",
"Nice Dreams",
"Nightmare at Bitter Creek",
"Nightmare Circus (a.k.a. The Barn of the Naked Dead or Terror Circus)",
"Nimed marmortahvlil",
"Ninja Strike Force",
"Ninth Gate, The",
"Nipernaadi",
"No Holds Barred",
"No Reservations",
"Notes on a Scandal",
"Not Without My Daughter",
"Now and Then",
"Nukitsamees",
"Nurse Betty",
"Nutcracker: The Motion Picture",
"Nutty Professor, The",
"Object of My Affection, The",
"O",
"Odyssey, The",
"Oh in Ohio, The",
"Orange County",
"Outside Chance of Maximilian Glick, The",
"Outside Out",
"Outsiders, The",
"Out to Sea",
"On Dangerous Ground (1952)",
"On Dangerous Ground (1996)",
"One, The",
"One Day In September",
"One Fine Day",
"One Special Night",
"One Trick Pony",
"Onion Movie, The",
"Only You",
"Opposite of Sex",
"Operation Petticoat",
"Orange County",
"Others, The",
"Out of Africa",
"on",
"Oxford Murders, The",
"Other Guys,The",
"Party Girl (1958)",
"Party Girl (1995)",
"P.S. I Love You",
"Passenger 57",
"Passion of Darkly Noon, The",
"Patriot, The",
"Payback",
"Peggy Sue Got Married",
"Perfect Murder, A",
"Pete's Dragon",
"Phenomenon",
"Phonebooth",
"Pianist, The",
"The Picture of Dorian Gray (film)",
"Pink Panther, The (1963)",
"Pirates (film), a Joone film",
"Pirates of Silicon Valley",
"Pitch Black (2000)",
"Planet 51",
"Planet of the Apes (2001)",
"Planet Terror",
"Poetic Justice",
"Porky's",
"Portrait of a Lady, The",
"Possesion",
"Premonition (1972)",
"Premonition (2004)",
"Premonition (2007)",
"Prime",
"Princess O'Rourke",
"Prom Night (1980)",
"Prom Night (2008)",
"Prophecy, The",
"PU-239",
"Punch Drunk Love",
"Purple Noon",
"Purple Rain",
"Pursuit of Happiness",
"Push",
"Queen Christina",
"Quick and the Dead, The",
"Quiz Show, The",
"Quo Vadis",
"Radio",
"Raggedy Rawney, The",
"Raise Your Voice",
"Rakeman",
"Ramona and Beezus",
"Ran",
"The Reader",
"Ready to Rumble",
"Real Life",
"Reasonable Man, A",
"REC",
"Reckless (1935)",
"Reckless (1951)",
"Reckless (1984)",
"Reckless (1995)",
"Red Danube, The",
"Reds",
"Redwoods",
"Reindeer Games",
"Remember Me",
"Remember My Name",
"The Rescuers Down Under",
"Resident Evil: Extinction",
"Restoration",
"Revolutionary Road",
"Return Engagement (1983)",
"Return Engagement (1990)",
"Return of the Pink Panther, The",
"Revenge of the Pink Panther",
"Right Stuff, The",
"Ringer, The",
"Rio (2011 film)",
"Ripley Under Ground",
"Ripley's Game",
"Road Warrior, The",
"Roadie",
"Robin Hood (2010)",
"RoboCop 2",
"RoboCop 3",
"Rocking Horse Winner, The",
"Rollerball",
"Romeo and Juliet (film)",
"Romeo and Juliet: Sealed with a Kiss",
"Romper Stomper",
"Room, The",
"Rooster Cogburn and the Lady",
"Roots",
"Röövlirahnu Martin",
"Ruby Cairo",
"Rumor Has It...",
"Run For Cover (1955)",
"Run For Cover (1995)",
"Run Lola Run",
"Rue Cases Negres",
"Runaways, The",
"Runaway Train",
"Running Man",
"Running Scared",
"Run Ronnie Run",
"Russians Are Coming the Russians Are Coming, The",
"Ruth",
"Sabrina",
"Saint Trinians",
"Sarfarosh",
"Sanctum",
"Sandwich Man, The",
"Santa Clause 2, The",
"Santa Clause 3: The Escape Clause, The",
"Santa Fe Trail",
"Savage Innocents, The",
"Say Anything...",
"Say It Isn't So",
"Scalphunters, The",
"Scarlett Letter, The",
"School for Scoundrels",
"Science of Sleep",
"Screamers",
"The Secret of Kells",
"The Secret Life of Bees",
"The Secret Life of Words",
"Secret Lives of Dentists, The",
"Secretary",
"Serpent and the Rainbow, The",
"Serpico",
"Sesame Street Presents Follow That Bird",
"Seven Pounds",
"Seventh Bullet, The",
"Sex And The Single Girl",
"Sex, Lies, and Videotape",
"Sgt. Bilko",
"Shakiest Gun in the West, The",
"Shampoo",
"Shrek the Halls",
"She's So Lovely",
"Shiloh",
"Shine",
"Shoot to Kill",
"Shooter",
"Shootist, The",
"Shop Around the Corner, The",
"Shadows in the sun",
"Sharky's Machine",
"Shopgirl",
"Short Circuit 2",
"Sicilian, The",
"Siege, The",
"Slacker",
"Slam Dunk Ernest",
"SLC Punk",
"Sleeper",
"Sleepers",
"Sleeping Dogs",
"Sleeping Dogs Lie (1998)",
"Sleeping Dogs Lie (2005)",
"Sleeping Dogs Lie (2006)",
"Smart People",
"Solaris",
"Something's Gotta Give",
"Son of the Mask",
"Song of Norway",
"Song of the South",
"Sordid Lives",
"Soul Men",
"Soul Man 1986",
"Space Cowboys",
"Sphere, The",
"Spun",
"Stalingrad",
"Stay",
"Stealing Harvard",
"Steamroller and the Violin, The",
"St. Elmo's Fire",
"Stepmom",
"Step Up 2: The Streets",
"Step Up 3D",
"Stepfather II",
"Stir Crazy",
"Stitch! The Movie",
"Stormy Monday",
"Story of O",
"Stalingrad",
"Straight Talk",
"Stranger on the Third Floor",
"The Stepfather (1987 film)",
"The Strangers",
"Strange Cargo",
"Strange Wilderness",
"Strangers With Candy",
"Strawberry Shortcake: The Sweet Dreams Movie",
"Street Smart",
"Stuck On You",
"Suckerpunch",
"Sügis",
"Summer School",
"Sumo of the Opera",
"Suvi",
"Swan Princess, The",
"S.W.A.T.",
"Sweet November",
"Sweet Land",
"Take The Lead",
"Taking Lives",
"Talented Mr. Ripley, The",
"That Was Then... This Is Now",
"Team of Speed, The",
"Team of Speed 2, The",
"Teeth",
"Tekkon Kinkreet",
"Tequilia Sunrise",
"Thank Your Lucky Stars",
"That Thing You Do!",
"The Twilight Saga: Breaking Dawn Part 1",
"The Twilight Saga: Breaking Dawn Part 2",
"Them! (1954)",
"Them (2006)",
"Things to Do in Denver When You're Dead",
"Thirteen Ghosts",
"Thirteenth Floor, The",
"They Fought For Their Country",
"They Live by Night",
"Think Big",
"This is England",
"This Boy's Life",
"Throw Momma from the Train",
"Thumbelina",
"Thunderbirds",
"Thursday",
"Tigger Movie, The",
"Time To Kill, A",
"Tinker Bell",
"Tinker Bell and the Lost Treasure",
"Tinker Bell and the Great Fairy Rescue",
"To Die For",
"To Gillian on Her 37th Birthday",
"Tomcats",
"Transporter, The",
"Transporter 2",
"Transporter 3",
"Tremors 2: Aftershocks",
"Tremors 3: Back to Perfection",
"Tremors 4: The Legend Begins",
"Trigger Effect, The",
"True Colors",
"True Confessions (1937 film)",
"True Story of Jesse James, The",
"Tuesdays with Morrie (film)",
"Turbo: A Power Rangers Movie",
"Two Weeks With Love",
"Two Lane Blacktop",
"Twin Peaks: Fire Walk With Me",
"Twins (film)",
"Tulnukas",
"The Time Traveler's Wife",
"The Blind Side",
"The Last Don",
"Ugly Truth, The",
"Ultimate Gift, The",
"Underworld",
"Unfaithful",
"Unhitched",
"United 93",
"Unknown (film)",
"Untraceable",
"Up in the Air",
"Up in Smoke",
"Uptown Saturday Night",
"U Turn",
"Under The Tuscan Sun",
"Unstable Fables",
"Used Cars",
"Valley Girl",
"Valentine's Day (film)",
"Valmont",
"Vanishing Point",
"VeggieTales: Lessons from the Sock Drawer",
"VeggieTales: Minnesota Cuke and the Search for Samson's Hairbrush",
"Very Long Engagement, A",
"Von Ryan's Express",
"Vampire's Kiss",
"Vampire Bat, The (1933)",
"Viimne reliikvia",
"Visioneers",
"Vertical Limit",
"W.",
"Wackness, The",
"Walk Like a Man",
"Walk on the Moon, A",
"Walk the Proud Land",
"Wall, The",
"Wanted",
"Warlock",
"Warriors of Virtue",
"Water (film)",
"Watership Down",
"Waterworld",
"Wash, The",
"We Can't Go Home Again",
"Welcome Home Roscoe Jenkins",
"Welcome to L.A.",
"Welcome To Mooseport",
"Welcome to the Jungle",
"We Own The Night",
"West Side Waltz, The",
"What's Eating Gilbert Grape?",
"What the Bleep Do We Know!?",
"What Planet Are You From?",
"What We Do Is Secret",
"When a Man Loves a Woman",
"When a Stranger Calls",
"When Darkness Falls",
"When in Rome",
"Why Did I Get Married?",
"Wild Child",
"Wild Hearts Can't Be Broken",
"Wind that Shakes the Barley, The",
"Wind Across the Everglades",
"Whatever Works",
"Whipped",
"Whisper of the Heart",
"White Chicks",
"White Oleander",
"With Honor's",
"Wild Wild West",
"Wildcats",
"Wit",
"Without Limits",
"Wizards",
"Wolfman, The",
"Woman's Secret, A",
"Women, The",
"Wild One, The",
"Wild Child",
"xXx: State of the Union",
"Y Tu Mama tambien",
"Year of the Dragon",
"Young Americans, The",
"Young Black Stallion, The",
"Youth In Revolt",
"Yellow Bird, The",
"Yes 2004/",
"Z",
"Zeitgeist: Addendum",
"Zeitgeist: Moving Forward",
"Zenon the Zequel",
"Zenon: Z3",
"Zero Day",
];